### ISSUE TITLE
type配置type=request, type=action有何不同

### ISSUE THREAD

**Issue by Tonylue** [kequandian/hub.crudless.zerocode#28]
文档里面action项配置，type=request, type=action有何不同
type=request和type=action传参（id）和{id}的区别
{
"title": "确认订单",
"type": "request",
"options": {
"outside": true,
"API": "/api/crud/order/orders/(id)/action/confirm"
}
},
{
"title": "上传结案",
"type": "action",
"options": {
"expect": {
"field": "status",
"value": "TO_BE_VERIFY"
},
"API": "/api/crud/order/orders/{id}/action/provide",
"outside": false
}

**Comment by Tonylue** [comment]
{
      "title": "确认订单",
      "type": "request",
      "options": {
        "outside": true,
        "API": "/api/crud/order/orders/(id)/action/confirm"
      }
    },
    {
      "title": "上传结案",
      "type": "action",
      "options": {
        "expect": {
          "field": "status",
          "value": "TO_BE_VERIFY"
        },
        "API": "/api/crud/order/orders/{id}/action/provide",
        "outside": false
      }

**Comment by a30f49** [comment]
已统一为  request
