### ISSUE TITLE
[ cg-api-cli ] 生成的后端代码中资源文件缺少SQL文件

### ISSUE THREAD

**Issue by zchengb** [kequandian/hub.crudless.zerocode#8]
该SQL文件用于后续自动装配后**初始化**所用。

**Comment by ye126** [comment]
已修复，目前会根据sql生成表结构  
效果如下
![image](https://user-images.githubusercontent.com/58674307/91689093-ff0e4080-eb95-11ea-9c7e-53af2d9cfa45.png)
